# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: opencfd/openfoam2106-default
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build tools
        run: sudo apt-get update && apt-get -y install build-essential cmake git
      
      - name: Clone submodules
        run:  |
            auth_header="$(git config --local --get http.https://github.com/.extraheader)"
            git submodule sync --recursive
            git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=2

      - name: Source OpenFOAM Environment
        run: sudo chmod +x /usr/lib/openfoam/openfoam2106/etc/openfoam

      - name: Make executables
        run: |
            sudo chmod +x Allwclean
            sudo chmod +x Allwmake
            /usr/lib/openfoam/openfoam2106/etc/openfoam ./Allwclean
            /usr/lib/openfoam/openfoam2106/etc/openfoam ./Allwmake